# Generated by Django 3.2 on 2022-08-24 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_article_vote2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='vote',
        ),
        migrations.RemoveField(
            model_name='article',
            name='vote2',
        ),
    ]
