services:
  postgres:
    image: postgres
    container_name: postgres
    networks:
      - main
    ports:
      - '5432:5432'
    volumes:
      - postgres_volumes:/var/lib/postgresql/data
    
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: always

  app:
    build:  .
    container_name: app
    networks:
      - main
    ports:
      - "8000"
    volumes:
      - .:/code/
    expose:
      - 8000
    depends_on:
      - postgres
    restart: always

  nginx:
      image: nginx
      command:  nginx -g 'daemon off;'
      container_name: nginx
      networks:
          - main
      volumes:
          - ./nginx.conf:/etc/nginx/nginx.conf
          - ./static:/app/static

      restart: always
      depends_on:
          - app
      ports:
          - '80:80'

volumes:
  postgres_volumes:
  app_static_volume:
  app_files_volume:
networks:
  main:

        
    
