# Generated by Django 3.2 on 2022-08-25 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_media', '0002_post_vote23'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='vote23',
        ),
    ]
